spring:
    application:
      name: sparkker
server:
  port: 8988 
data:
  feed:
     online: false
---
spring:
   profiles: default
eureka:
    password: user
    client:
        serviceUrl:
            defaultZone: http://user:${eureka.password}@localhost:9999/eureka/
         