spring:
    application:
      name: sparkker
server:
  port: 8988 
data:
  feed:
     online: true
rules:
   file:
      path: C:/development/sparkker/src/main/resources/org/vferrer/sparkker/service/rules.dlr
---
spring:
   profiles: default
eureka:
    password: user
    client:
        serviceUrl:
            defaultZone: http://user:${eureka.password}@localhost:9999/eureka/
            
         